services:
  - type: web
    name: houseprice
    runtime: docker
    repo: https://github.com/joecjoecjoec/houseprice.git
    branch: main
    plan: free
    autoDeploy: true
    healthCheckPath: /health
